name: CI

on:
  schedule:
    - cron: 0 0 * * * # at 00:00 AM (UTC) on everyday.
  push:
    branches:
      - ci/**
  workflow_dispatch: {}

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: awesome-useful-websites
        uses: younho9/awesome-websites@main
        with:
          notion_api_token: ${{ secrets.NOTION_API_TOKEN }}
          notion_database_url: ${{ secrets.USEFUL_NOTION_DATABASE_URL }}
          gist_token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ secrets.USEFUL_GIST_ID }}
          file_name: awesome-useful-websites.md

      - id: awesome-inspiring-websites
        uses: younho9/awesome-websites@main
        with:
          notion_api_token: ${{ secrets.NOTION_API_TOKEN }}
          notion_database_url: ${{ secrets.INSPIRING_NOTION_DATABASE_URL }}
          gist_token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ secrets.INSPIRING_GIST_ID }}
          file_name: awesome-inspiring-websites.md

      - id: awesome-korean-resume
        uses: younho9/awesome-websites@main
        with:
          notion_api_token: ${{ secrets.NOTION_API_TOKEN }}
          notion_database_url: ${{ secrets.RESUME_NOTION_DATABASE_URL }}
          gist_token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ secrets.RESUME_GIST_ID }}
          file_name: awesome-korean-resume.md
          template_name: korean-resume-template.md
